
class PDFGenerationServiceClass {
  generateCoursePDF(course: any): string {
    const { name, description, materials, estimatedTime } = course;
    
    // Create structured PDF content
    let pdfContent = `
<!DOCTYPE html>
<html>
<head>
    <title>${name}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
        .header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 20px; margin-bottom: 30px; }
        .title { font-size: 24px; font-weight: bold; color: #333; margin-bottom: 10px; }
        .subtitle { font-size: 14px; color: #666; }
        .section { margin-bottom: 25px; }
        .section-title { font-size: 18px; font-weight: bold; color: #444; margin-bottom: 15px; border-left: 4px solid #0066cc; padding-left: 10px; }
        .material { margin-bottom: 20px; padding: 15px; background-color: #f9f9f9; border-radius: 5px; }
        .material-title { font-size: 16px; font-weight: bold; color: #333; margin-bottom: 10px; }
        .material-content { font-size: 14px; line-height: 1.8; text-align: justify; }
        .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #ccc; font-size: 12px; color: #666; }
        @media print { body { margin: 20px; } }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">${name}</div>
        <div class="subtitle">Educational Course Material</div>
        <div class="subtitle">Estimated Duration: ${estimatedTime} minutes</div>
    </div>
    
    <div class="section">
        <div class="section-title">Course Overview</div>
        <div class="material-content">${description}</div>
    </div>`;

    // Add course materials
    materials.forEach((material: any, index: number) => {
      pdfContent += `
    <div class="section">
        <div class="section-title">Section ${index + 1}: ${material.title}</div>
        <div class="material">
            <div class="material-content">${this.formatContent(material.content)}</div>
        </div>
    </div>`;
    });

    pdfContent += `
    <div class="footer">
        Generated by Questora AI | Course completion required before assessment
    </div>
</body>
</html>`;

    return this.convertToPDFDataUrl(pdfContent);
  }

  private formatContent(content: string): string {
    // Format content for better PDF display
    return content
      .replace(/\n\n/g, '</p><p>')
      .replace(/\n/g, '<br>')
      .replace(/^/, '<p>')
      .replace(/$/, '</p>')
      .replace(/<p><\/p>/g, '')
      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.*?)\*/g, '<em>$1</em>');
  }

  private convertToPDFDataUrl(htmlContent: string): string {
    // Create a data URL that can be used for PDF download
    const blob = new Blob([htmlContent], { type: 'text/html' });
    return URL.createObjectURL(blob);
  }

  downloadPDF(dataUrl: string, filename: string): void {
    const link = document.createElement('a');
    link.href = dataUrl;
    link.download = `${filename}.html`; // Will be opened as PDF in browser
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }
}

export const PDFGenerationService = new PDFGenerationServiceClass();
