// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twmkejpijlwnxmxtvgmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3bWtlanBpamx3bnhteHR2Z21uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMTc0OTUsImV4cCI6MjA2NjU5MzQ5NX0.imX0VPJx4wR2cT7rZIhonWv2LVERPx5CW1DfEOR3fC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);